#!/bin/bash
# ar-consumer daemon
# chkconfig: 345 20 80
# description: ar-consumer daemon
# processname: ar-consumer

. /etc/rc.d/init.d/functions
PROG_NAME="ar-consumer"
DAEMON_PATH="/usr/bin/ar-consumer"
USER="arstats"

case "$1" in
start)
	echo -n $"Starting $PROG_NAME: "
	daemon --user $USER $DAEMON_PATH start
	echo
;;
status)
	$DAEMON_PATH status
;;
stop)
	echo -n $"Stopping $PROG_NAME: "
	daemon --user $USER $DAEMON_PATH stop
	echo
;;
restart)
	echo -n $"Restarting $PROG_NAME: "
        daemon --user $USER $DAEMON_PATH restart
	echo
;;
*)
        echo "Usage: $0 {status|start|stop|restart}"
        exit 1
esac

