#!/bin/bash
# argo-egi-consumer daemon
# chkconfig: 345 20 80
# description: argo-egi-consumer daemon
# processname: argo-egi-consumer

. /etc/rc.d/init.d/functions
PROG_NAME="argo-egi-consumer"
CONFIG="/etc/argo-egi-consumer/consumer.conf"
DAEMON_PATH="/usr/bin/argo-egi-consumer.py"

case "$1" in
start)
	echo -n $"Starting $PROG_NAME: "
	daemon $DAEMON_PATH --start --config $CONFIG
	echo
;;
status)
	$DAEMON_PATH --status --config $CONFIG
;;
stop)
	echo -n $"Stopping $PROG_NAME: "
	daemon $DAEMON_PATH --stop --config $CONFIG
	echo
;;
reload)
	echo -n $"Reloading $PROG_NAME: "
	daemon $DAEMON_PATH --reload --config $CONFIG
	echo
;;
restart)
	echo -n $"Restarting $PROG_NAME: "
	daemon $DAEMON_PATH --restart --config $CONFIG
	echo
;;
*)
	echo "Usage: $0 {status|start|stop|restart|reload}"
	exit 1
esac

